language: ruby
cache: bundler

services:
  - redis-server
  - elasticsearch

addons:
  code_climate:
    repo_token: 'a225f07862617f4592fdcd75260bae259fdb6a6c57f7a4ee6df64b18fa38837b'

rvm:
  - "2.2.1"

# uncomment this line if your project needs to run something other than `rake`:
script:
  - bundle exec rake db:migrate --trace RAILS_ENV=test
  - bundle exec rake db:test:prepare
  - bundle exec rake feed:recreate_index --trace RAILS_ENV=test
  - bundle exec rspec spec

before_script:
# - rm Gemfile.lock
  - /usr/share/elasticsearch/bin/elasticsearch -v
  - sudo /usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-mapper-attachments/2.4.3
  - sudo service elasticsearch restart
  - cp config/application.travis.yml config/application.yml
  - mysql -e 'create database stream_alert_test'
