:concurrency: 25
development:
  :pidfile: tmp/pids/sidekiq-main.pid

production:
  :pidfile: ../../shared/tmp/pids/sidekiq-main.pid
  :logfile: ../../shared/log/sidekiq-main.log
  :concurrency: 25

:queues:
  - mailers
  - default
  - indexer
  - alert_result
